//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogAcesso
    {
        public int idlog { get; set; }
        public Nullable<int> idusuario { get; set; }
        public Nullable<System.DateTime> dataHoraAcesso { get; set; }
        public Nullable<System.DateTime> DataHoraSaida { get; set; }
    
        public virtual Acesso Acesso { get; set; }
    }
}
