//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModuloWebEntities : DbContext
    {
        public ModuloWebEntities()
            : base("name=ModuloWebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Acesso> Acesso { get; set; }
        public virtual DbSet<Competidor> Competidor { get; set; }
        public virtual DbSet<DataNacional> DataNacional { get; set; }
        public virtual DbSet<Estados> Estados { get; set; }
        public virtual DbSet<LogAcesso> LogAcesso { get; set; }
        public virtual DbSet<Modalidade> Modalidade { get; set; }
        public virtual DbSet<Notas> Notas { get; set; }
        public virtual DbSet<Noticia> Noticia { get; set; }
        public virtual DbSet<Parceiro> Parceiro { get; set; }
        public virtual DbSet<SkillModalidade> SkillModalidade { get; set; }
        public virtual DbSet<Skills> Skills { get; set; }
    }
}
