//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notas
    {
        public int idNota { get; set; }
        public Nullable<int> idCompetidor { get; set; }
        public Nullable<int> s1 { get; set; }
        public Nullable<int> s2 { get; set; }
        public Nullable<int> s3 { get; set; }
        public Nullable<int> s4 { get; set; }
        public Nullable<int> s5 { get; set; }
        public Nullable<int> s6 { get; set; }
    
        public virtual Competidor Competidor { get; set; }
    }
}
