//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Noticia
    {
        public int id { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string titulo { get; set; }
        public string noticia1 { get; set; }
        public string status { get; set; }
    }
}
