//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillModalidade
    {
        public int id { get; set; }
        public Nullable<int> idskill { get; set; }
        public string idmodalidade { get; set; }
    
        public virtual Modalidade Modalidade { get; set; }
        public virtual Skills Skills { get; set; }
    }
}
